name: py37env
channels:
  - defaults
dependencies:
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=22.3.1=py37haa95532_0
  - python=3.7.16=h6244533_0
  - setuptools=65.6.3=py37haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bottleneck==1.4.0
      - branca==0.8.2
      - cachetools==5.5.2
      - cffi==1.15.1
      - chardet==3.0.4
      - click==8.1.8
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - cryptography==45.0.7
      - cycler==0.11.0
      - cython==3.0.12
      - cytoolz==0.12.3
      - dask==2022.2.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - distributed==2022.2.0
      - easydict==1.13
      - entrypoints==0.4
      - flask==1.0.2
      - flatbuffers==25.12.19
      - folium==0.16.0
      - fsspec==2023.1.0
      - gast==0.4.0
      - gevent==22.10.2
      - google-auth==2.45.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.62.3
      - h5py==2.9.0
      - heapdict==1.0.1
      - idna==2.8
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - itsdangerous==2.1.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - llvmlite==0.39.1
      - locket==1.0.0
      - lxml==5.4.0
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.0.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.5
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - nltk==3.8.1
      - numba==0.56.4
      - numexpr==2.8.6
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opencv-python==4.12.0.88
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.3.5
      - parso==0.8.5
      - partd==1.4.1
      - patsy==1.0.2
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - prettytable==3.7.0
      - prompt-toolkit==3.0.48
      - protobuf==3.19.6
      - psutil==7.2.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyecharts==2.0.9
      - pygments==2.17.2
      - pymysql==1.1.1
      - pyopenssl==25.3.0
      - pyparsing==3.1.4
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - pyrsistent==0.19.3
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pywin32==308
      - pyyaml==3.13
      - pyzmq==26.2.1
      - qdarkstyle==3.2.3
      - qtawesome==1.4.0
      - qtconsole==5.4.4
      - qtpy==2.4.3
      - regex==2024.4.16
      - requests==2.21.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==0.20.3
      - scipy==1.7.3
      - seaborn==0.9.0
      - simplejson==3.20.2
      - six==1.17.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - sqlalchemy==2.0.45
      - statsmodels==0.13.5
      - sympy==1.10.1
      - tables==3.7.0
      - tblib==2.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-intel==2.11.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tifffile==2021.11.2
      - toolz==0.12.1
      - torch==1.9.0
      - torchaudio==0.9.0
      - torchvision==0.10.0
      - tornado==6.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - urllib3==1.24.3
      - wcwidth==0.2.14
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - xyzservices==2023.2.0
      - zict==2.2.0
      - zipp==3.15.0
      - zope-event==5.0
      - zope-interface==6.4.post2
prefix: D:\1anaconda\envs\py37env
